CREATE TABLE [dbo].[ee_profile_online_old] (
    [tid]                 VARCHAR (10)  NOT NULL,
    [orig_addr]           VARCHAR (200) NULL,
    [orig_city]           VARCHAR (75)  NULL,
    [orig_state]          VARCHAR (5)   NULL,
    [orig_zip]            VARCHAR (10)  NULL,
    [orig_country]        VARCHAR (5)   NULL,
    [orig_home_phone]     VARCHAR (25)  NULL,
    [orig_housing_status] VARCHAR (50)  NULL,
    [dest_addr]           VARCHAR (200) NULL,
    [dest_city]           VARCHAR (75)  NULL,
    [dest_state]          VARCHAR (5)   NULL,
    [dest_zip]            VARCHAR (10)  NULL,
    [dest_country]        VARCHAR (5)   NULL,
    [dest_home_phone]     VARCHAR (25)  NULL,
    [dest_work_phone]     VARCHAR (25)  NULL,
    [dest_work_ext]       INT           NULL,
    [dest_home_email]     VARCHAR (150) NULL,
    [dest_work_email]     VARCHAR (150) NULL,
    [dest_housing_status] VARCHAR (50)  NULL,
    [temp_addr]           VARCHAR (200) NULL,
    [temp_city]           VARCHAR (75)  NULL,
    [temp_state]          VARCHAR (5)   NULL,
    [temp_zip]            VARCHAR (10)  NULL,
    [temp_country]        VARCHAR (5)   NULL,
    [primary_email]       CHAR (1)      NULL,
    [move_type]           VARCHAR (50)  NULL,
    [status]              VARCHAR (5)   NULL,
    [status_date]         DATETIME      NULL,
    [updated_by]          VARCHAR (150) NULL,
    [updated_date]        DATETIME      NULL,
    [cell_phone]          VARCHAR (25)  NULL,
    CONSTRAINT [XPKee_profile_online] PRIMARY KEY CLUSTERED ([tid] ASC)
);

